// document.querySelectorAll('figure.wp-block-uagb-image__figure')[0].classList.add('checkbox');
let ba9att = [
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[0],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[1],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[2],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[3],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[4],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[5],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[6],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[7],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[8],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[9],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[10],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[11],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[12],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[13],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[14],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[15],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[16],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[17],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[18],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[19],
    document.querySelectorAll('figure.wp-block-uagb-image__figure')[18]];

   ba9att[0].onclick = function(){
    localStorage.setItem('ba9','100');
    this.classList.add('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }   
   ba9att[1].onclick = function(){
    localStorage.setItem('ba9','200');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[2].onclick = function(){
    localStorage.setItem('ba9','300');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[3].onclick = function(){
    localStorage.setItem('ba9','400');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }  
    ba9att[4].onclick = function(){
    localStorage.setItem('ba9','500');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[5].onclick = function(){
    localStorage.setItem('ba9','600');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[6].onclick = function(){
    localStorage.setItem('ba9','700');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[7].onclick = function(){
    localStorage.setItem('ba9','800');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[8].onclick = function(){
    localStorage.setItem('ba9','900');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[9].onclick = function(){
    localStorage.setItem('ba9','1200');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[10].onclick = function(){
    localStorage.setItem('ba9','1500');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[11].onclick = function(){
    localStorage.setItem('ba9','1800');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[12].onclick = function(){
    localStorage.setItem('ba9','2000');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[13].onclick = function(){
    localStorage.setItem('ba9','2100');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[14].onclick = function(){
    localStorage.setItem('ba9','2400');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[15].onclick = function(){
    localStorage.setItem('ba9','2500');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[16].onclick = function(){
    localStorage.setItem('ba9','3000');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   }
   ba9att[17].onclick = function(){
    localStorage.setItem('ba9','3500');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[18].classList.remove('checkbox');
   } 
    ba9att[18].onclick = function(){
    localStorage.setItem('ba9','4000');
    this.classList.add('checkbox');
    ba9att[0].classList.remove('checkbox');
    ba9att[1].classList.remove('checkbox');
    ba9att[2].classList.remove('checkbox');
    ba9att[3].classList.remove('checkbox');
    ba9att[4].classList.remove('checkbox');
    ba9att[5].classList.remove('checkbox');
    ba9att[6].classList.remove('checkbox');
    ba9att[7].classList.remove('checkbox');
    ba9att[8].classList.remove('checkbox');
    ba9att[9].classList.remove('checkbox');
    ba9att[10].classList.remove('checkbox');
    ba9att[11].classList.remove('checkbox');
    ba9att[12].classList.remove('checkbox');
    ba9att[13].classList.remove('checkbox');
    ba9att[14].classList.remove('checkbox');
    ba9att[15].classList.remove('checkbox');
    ba9att[16].classList.remove('checkbox');
    ba9att[17].classList.remove('checkbox');
   }
   